version: '3'
services:
    php:
        image: php:7.2-fpm
        volumes:
            - ./php:/code
    nginx:
        build: nginx
        ports:
            - "8888:80"
        volumes:
            - ./nginx:/code
        depends_on:
            - php

